---
title: "Introduction to the NicheMapR microclimate model"
author: "Michael Kearney"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ectotherm model tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
 eval = TRUE
)
```
This vignette provides a detailed tutorial of the Niche Mapper ectotherm model as implemented in the package *NicheMapR*. It only considers the base heat and (partial) water budget model. For details on the implementation of the Dynamic Energy Budget model (for simulating growth, development and reproduction as well as full water budgets), see the *DEB-model-tutorial* vignette (on the to do list!).

## Overview

The *NicheMapR* ectotherm model is run with the function *ectotherm*. This includes computations of steady state and transient heat budgets for animals that do not produce signficant metabolic heat. It includes a range of morphological, physiological and behavioural options to capture how organisms exchange heat and water with their environments, and to compute the consequences of this for body temperature, activity constraints and different aspects of the mass budget. It is designed to take the output of the *NicheMapR* microclimate model as the driving environmental inputs, but the user can construct custom versions of these if desired (see section xxx).

### Basic operation: modelling heat and activity budgets for the average day of each month

As with the microclimate model tutoria, this first example involves the most basic case of running the model to produce 12 days of output, one for each month of the year. Try running the model with all default inputs.
