      SUBROUTINE CLIMBER
C     NICHEMAPR: SOFTWARE FOR BIOPHYSICAL MECHANISTIC NICHE MODELLING

C     COPYRIGHT (C) 2018 MICHAEL R. KEARNEY AND WARREN P. PORTER

C     THIS PROGRAM IS FREE SOFTWARE: YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C     IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C     THE FREE SOFTWARE FOUNDATION, EITHER VERSION 3 OF THE LICENSE, OR (AT
C      YOUR OPTION) ANY LATER VERSION.

C     THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
C     WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C     MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
C     GENERAL PUBLIC LICENSE FOR MORE DETAILS.

C     YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C     ALONG WITH THIS PROGRAM. IF NOT, SEE HTTP://WWW.GNU.ORG/LICENSES/.

C	  THIS PROGRAM IS CALLED BY THERMO WHEN ANIMAL IS CLIMBING TO ESCAPE
C     HIGH OR LOW TEMPERATURES

      IMPLICIT NONE

      DOUBLE PRECISION A1,A2,A3,A4,A4B,A5,A6,ACTHR,AL,AMASS,ANDENS,AREF
      DOUBLE PRECISION ASIL,ASILP,ATOT,BREF,CREF,CUSTOMGEOM,DEPSEL
      DOUBLE PRECISION DEPSUB,EMISAN,EMISSB,EMISSK,F12,F13,F14,F15,F16
      DOUBLE PRECISION F21,F23,F24,F25,F26,F31,F32,F41,F42,F51,F52,F61
      DOUBLE PRECISION FATOSB,FATOSK,FLSHCOND,FLUID,G,HSHSOI,HSOIL
      DOUBLE PRECISION MSHSOI,MSOIL,NEWDEP,PHI,PHIMAX,PHIMIN,PSHSOI
      DOUBLE PRECISION PSOIL,PTCOND,PTCOND_ORIG,QCOND,QCONV,QIRIN,QIROUT
      DOUBLE PRECISION QMETAB,QRESP,QSEVAP,QSOL,QSOLAR,QSOLR,RELHUM,RH
      DOUBLE PRECISION RHO1_3,RHREF,SHADE,SHP,SIDEX,SIG,SUBTK,TA,TALOC
      DOUBLE PRECISION TANNUL,TBASK,TC,TCORES,TDIGPR,TEMERGE,TIME,TMAXPR
      DOUBLE PRECISION TMINPR,TOBJ,TPREF,TQSOL,TRANS1,TREF,TSHSOI,TSKY
      DOUBLE PRECISION TSKYC,TSOIL,TSUB,TSUBST,TWING,VEL,VLOC,VREF,WQSOL
      DOUBLE PRECISION Z,ZSOIL
      
      INTEGER CLIMBING,IHOUR,GEOMETRY,MICRO,NODNUM,WINGMOD,WINGCALC
      
      CHARACTER*1 BURROW,CKGRSHAD,CLIMB,CREPUS,DAYACT,NOCTURN
      
      DIMENSION ACTHR(25),CUSTOMGEOM(8),DEPSEL(25),HSHSOI(25),HSOIL(25)
      DIMENSION MSHSOI(25),MSOIL(25),PSHSOI(25),PSOIL(25),QSOL(25)
      DIMENSION RH(25),RHREF(25),SHP(3),TALOC(25),TCORES(25),TIME(25)
      DIMENSION TREF(25),TSHSOI(25),TSKYC(25),TSOIL(25),TSUB(25)
      DIMENSION VLOC(25),VREF(25),Z(25),ZSOIL(10)

      COMMON/BEHAV1/DAYACT,BURROW,CLIMB,CKGRSHAD,CREPUS,NOCTURN
      COMMON/BEHAV2/GEOMETRY,NODNUM,CUSTOMGEOM,SHP
      COMMON/BEHAV3/ACTHR
      COMMON/CLIMB/CLIMBING
      COMMON/DEPTHS/DEPSEL,TCORES
      COMMON/ENVAR1/QSOL,RH,TSKYC,TIME,TALOC,TREF,RHREF
      COMMON/ENVAR2/TSUB,VREF,Z,TANNUL,VLOC
      COMMON/FUN1/QSOLAR,QIRIN,QMETAB,QRESP,QSEVAP,QIROUT,QCONV,QCOND
      COMMON/FUN2/AMASS,RELHUM,ATOT,FATOSK,FATOSB,EMISAN,SIG,FLSHCOND
      COMMON/FUN3/AL,TA,VEL,PTCOND,SUBTK,DEPSUB,TSUBST,PTCOND_ORIG
      COMMON/SOIL/TSOIL,TSHSOI,ZSOIL,MSOIL,MSHSOI,PSOIL,PSHSOI,HSOIL,
     & HSHSOI
      COMMON/TPREFR/TMAXPR,TMINPR,TDIGPR,TPREF,TBASK,TEMERGE
      COMMON/TREG/TC
      COMMON/WDSUB1/ANDENS,ASILP,EMISSB,EMISSK,FLUID,G,IHOUR
      COMMON/WDSUB2/QSOLR,TOBJ,TSKY,MICRO
      COMMON/WINGFUN/RHO1_3,TRANS1,AREF,BREF,CREF,PHI,F21,F31,F41,F51
     & ,SIDEX,WQSOL,PHIMIN,PHIMAX,TWING,F12,F32,F42,F52,F61,TQSOL,A1,A2
     & ,A3,A4,A4B,A5,A6,F13,F14,F15,F16,F23,F24,F25,F26,WINGCALC,WINGMOD
      COMMON/WSOLAR/ASIL,SHADE
      COMMON/WUNDRG/NEWDEP

      IF ((TREF(IHOUR) .GE. TMINPR).AND.(TREF(IHOUR) .LE. TPREF)) THEN
C      IT'S OK UP HIGH
C      IF (TREF(IHOUR) .LE. TDIGPR)THEN
C        CLIMB TO REFERENCE HEIGHT - USUALLY 1.2 TO 2M, REPORTING AS 150 CM HEIGHT
          DEPSEL(IHOUR) = 150.0
C        REFERENCE HEIGHT AIR TEMPERATURE IS THE SAME IN SUN OR SHADE.
          TA = TREF(IHOUR)
          VEL = VREF(IHOUR)
          CLIMBING = 1
C        NO ASSUMPTION OF INCREASE IN SHADE DUE TO CLIMBING.  MAY STILL BE IN THE SUN.
C        ENDIF
      ENDIF
      RETURN
      END