      SUBROUTINE JAC (NEQ, T, Y, ML, MU, PD, NRPD)
C     A DUMMY SUBROUTINE FOR LSODE WHEN A NON-STIFF PROBLEM
      DOUBLE PRECISION PD, T, Y
      INTEGER ML,MU,NEQ,NRPD
      DIMENSION Y(1), PD(NRPD,1)
      RETURN
      end