      SUBROUTINE MET

C     NICHEMAPR: SOFTWARE FOR BIOPHYSICAL MECHANISTIC NICHE MODELLING

C     COPYRIGHT (C) 2018 MICHAEL R. KEARNEY AND WARREN P. PORTER

C     THIS PROGRAM IS FREE SOFTWARE: YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C     IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C     THE FREE SOFTWARE FOUNDATION, EITHER VERSION 3 OF THE LICENSE, OR (AT
C      YOUR OPTION) ANY LATER VERSION.

C     THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
C     WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C     MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
C     GENERAL PUBLIC LICENSE FOR MORE DETAILS.

C     YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C     ALONG WITH THIS PROGRAM. IF NOT, SEE HTTP://WWW.GNU.ORG/LICENSES/.

C      THIS SUBROUTINE METABOLISM

      IMPLICIT NONE

      DOUBLE PRECISION ACTHR,AL,ALT,AMASS,AIRVOL,CO2MOL
      DOUBLE PRECISION ANDENS,AREA,ASILP,ATOT
      DOUBLE PRECISION BP,DEPSUB,EMISAN,EMISSB,EMISSK
      DOUBLE PRECISION FATCOND,FATOSK,FATOSB,FLSHCOND,FLUID,G,GMASS
      DOUBLE PRECISION ASEMAJR,BSEMINR,CSEMINR
      DOUBLE PRECISION QCOND,QCONV,QIRIN,QIROUT,PTCOND_ORIG
      DOUBLE PRECISION QMETAB,QRESP,QSEVAP,QSOLAR,QSOLR,QSWEAT
      DOUBLE PRECISION PTCOND,R,RELHUM,SIG,SUBTK,TEMERGE
      DOUBLE PRECISION TA,TC,TDIGPR,TMAXPR,TMINPR,TSKIN,TOBJ,TBASK
      DOUBLE PRECISION TR,TSKY,TSUBST,VEL,WEVAP,XTRY,H2O_BALPAST
      DOUBLE PRECISION TLUNG,EXTREF,RQ,GEVAP,DELTAR,R1,RINSUL,VOL
      DOUBLE PRECISION TPREF,MLO2,GH2OMET,DEBQMET
      DOUBLE PRECISION CUSTOMGEOM,MR_1,MR_2,MR_3,SHP,SIDEX,WQSOL
      DOUBLE PRECISION MLO2_INIT,GH2OMET_INIT,DEBQMET_INIT,NWASTE
      DOUBLE PRECISION T_A,T_AL,T_AH,T_L,T_H,T_REF,TCORR,DRYFOOD,FAECES
      DOUBLE PRECISION RHO1_3,TRANS1,AREF,BREF,CREF,PHI,F21,F31,F41,F51
     &    ,PHIMIN,PHIMAX,TWING,F12,F32,F42,F52,F23,F24,F25,F26
     &,F61,TQSOL,A1,A2,A3,A4,A4B,A5,A6,F13,F14,F15,F16
      DOUBLE PRECISION FLYTIME,FLYSPEED,FLYMETAB

      INTEGER IHOUR,MICRO,GEOMETRY,NODNUM,DEB1,WINGCALC
      INTEGER WINGMOD
      INTEGER FLIGHT,FLYER,FLYTEST,CLIMBING

      CHARACTER*1 BURROW,DAYACT,CLIMB,CKGRSHAD,CREPUS,NOCTURN

      DIMENSION ACTHR(25)
      DIMENSION CUSTOMGEOM(8),SHP(3)
      DIMENSION MLO2(24),GH2OMET(24),DEBQMET(24),DRYFOOD(24),
     &    FAECES(24),NWASTE(24)

      COMMON/FUN1/QSOLAR,QIRIN,QMETAB,QRESP,QSEVAP,QIROUT,QCONV,QCOND
      COMMON/FUN2/AMASS,RELHUM,ATOT,FATOSK,FATOSB,EMISAN,SIG,FLSHCOND
      COMMON/FUN3/AL,TA,VEL,PTCOND,SUBTK,DEPSUB,TSUBST,PTCOND_ORIG
      COMMON/FUN4/TSKIN,R,WEVAP,TR,ALT,BP,H2O_BALPAST
      COMMON/WINGFUN/RHO1_3,TRANS1,AREF,BREF,CREF,PHI,F21,F31,F41,F51
     &,SIDEX,WQSOL,PHIMIN,PHIMAX,TWING,F12,F32,F42,F52
     &,F61,TQSOL,A1,A2,A3,A4,A4B,A5,A6,F13,F14,F15,F16,F23,F24,F25,F26
     &,WINGCALC,WINGMOD
      COMMON/WDSUB1/ANDENS,ASILP,EMISSB,EMISSK,FLUID,G,IHOUR
      COMMON/WDSUB2/QSOLR,TOBJ,TSKY,MICRO
      COMMON/WMET/QSWEAT
      COMMON/TPREFR/TMAXPR,TMINPR,TDIGPR,TPREF,TBASK,TEMERGE
      COMMON/BEHAV1/DAYACT,BURROW,CLIMB,CKGRSHAD,CREPUS,NOCTURN
      COMMON/BEHAV2/GEOMETRY,NODNUM,CUSTOMGEOM,SHP
      COMMON/BEHAV3/ACTHR
      COMMON/REVAP1/TLUNG,DELTAR,EXTREF,RQ,MR_1,MR_2,MR_3,DEB1
      COMMON/REVAP2/GEVAP,AIRVOL,CO2MOL
      COMMON/ANPARMS/RINSUL,R1,AREA,VOL,FATCOND
      COMMON/ELLIPS/ASEMAJR,BSEMINR,CSEMINR
      COMMON/GUESS/XTRY
      COMMON/TREG/TC
      COMMON/DEBRESP/MLO2,GH2OMET,DEBQMET,MLO2_INIT,GH2OMET_INIT,
     &    DEBQMET_INIT,DRYFOOD,FAECES,NWASTE
      COMMON/ARRHEN/T_A,T_AL,T_AH,T_L,T_H,T_REF
      COMMON/FLY/FLYTIME,FLYSPEED,FLYMETAB,FLIGHT,FLYER,FLYTEST
      COMMON/CLIMB/CLIMBING

      GMASS=AMASS*1000.
      TC = XTRY

      IF(DEB1.EQ.1)THEN
C     USING DEB MODEL TO GET QMETAB, SKIP THE REGRESSIONS!
       TCORR=EXP(T_A*(1./(273.15+T_REF)-1./(273.15+TC)))/(1+EXP(T_AL
     & *(1./(273.15+TC)-1./T_L))+EXP(T_AH*(1/T_H-1./(273.15+TC))))
       IF(IHOUR.EQ.1)THEN
        QMETAB = DEBQMET_INIT*TCORR
       ELSE
        QMETAB = DEBQMET(IHOUR-1)*TCORR
       ENDIF
      ELSE
C      USE REGRESSION
C      LIZARD REGRESSION
       IF(TC .GT. 50)THEN
C       CAP METABOLIC RATE EQUATION WITH MAX OF TC = 50
        QMETAB = 0.0056*10.**(MR_3*50)*MR_1*GMASS**MR_2
        GOTO 101
       ENDIF
       IF(TC.LE.TPREF)THEN
        IF(TC.GE.1.0)THEN
C        ACCEPTABLE TEMPERATURE RANGE
         QMETAB=0.0056*10.**(MR_3*TC)*MR_1*GMASS**MR_2
        ELSE
         QMETAB = 0.01
        ENDIF
       ELSE
C       TOO HOT
C       ALLOWING TCORE TO BE A LITTLE HIGHER THAN TMAX PREFERRED SO THAT THERMOREGULATION
C       BEHAVIORS WILL BE INVOKED TO SELECT MORE MODERATE MICROCLIMATE CONDITIONS
        QMETAB = 0.0056*10.**(MR_3*(TMAXPR+0.5))*MR_1*GMASS**MR_2
       ENDIF
      ENDIF

      IF(FLYTEST.EQ.1)THEN
       QMETAB=QMETAB+FLYMETAB*AMASS*1000
      ENDIF

101   CONTINUE
      RETURN
      END
