      SUBROUTINE OSUB2(T,Y,TRANCT,NDAYY)

C     NICHEMAPR: SOFTWARE FOR BIOPHYSICAL MECHANISTIC NICHE MODELLING

C     COPYRIGHT (C) 2018 MICHAEL R. KEARNEY AND WARREN P. PORTER

C     THIS PROGRAM IS FREE SOFTWARE: YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C     IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C     THE FREE SOFTWARE FOUNDATION, EITHER VERSION 3 OF THE LICENSE, OR (AT
C      YOUR OPTION) ANY LATER VERSION.

C     THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
C     WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C     MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
C     GENERAL PUBLIC LICENSE FOR MORE DETAILS.

C     YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C     ALONG WITH THIS PROGRAM. IF NOT, SEE HTTP://WWW.GNU.ORG/LICENSES/.

C     THIS SUBROUTINE SAVES OUTPUT FROM SUBROUTINE GEAR, THE NUMERICAL INTEGRATOR FOR TRANSIENTS

      USE AACOMMONDAT
      IMPLICIT NONE

      DOUBLE PRECISION A1,A2,A3,A4,A4B,A5,A6,ABSMAX,ABSMIN,AEFF,ALT
      DOUBLE PRECISION AMASS,AREF,ATOT,BP,BREF,CONTDEPTH,CONVAR,CORE
      DOUBLE PRECISION CREF,CUTFA,EMISAN,F12,F13,F14,F15,F16,F21,F23,F24
      DOUBLE PRECISION F25,F26,F31,F32,F41,F42,F51,F52,F61,FATOSB,FATOSK
      DOUBLE PRECISION FLSHCOND,GCUT,GEVAP,GEYES,GMASS,GRESP,H2O_BALPAST
      DOUBLE PRECISION HC,HD,HOUR,O2MAX,O2MIN,PCTEYE,PEYES,PHI,PHIMAX
      DOUBLE PRECISION PHIMIN,QCOND,QCONV,QIRIN,QIROUT,QMETAB,QRESP
      DOUBLE PRECISION QSEVAP,QSOLAR,R,RELHUM,RHO1_3,SIDEX,SIG,SKINT
      DOUBLE PRECISION SKINW,SPHEAT,T,TBASK,TDIGPR,TEMERGE,TMAXPR,TMINPR
      DOUBLE PRECISION TPREF,TQSOL,TR,TRANS1,TSKIN,TWING,WCUT,WEVAP
      DOUBLE PRECISION WEYES,WQSOL,WRESP,Y
      DOUBLE PRECISION CONTH,CONTW,CONTVOL,CONTDEP,CONTHOLE,CONTWET,
     & RAINMULT,RAINFALL,QSOL,RH,TSKYC,TIME,TALOC,TREF,RHREF,HRN

      INTEGER IT,LIVE,NDAYY,TRANCT,WINGMOD,WINGCALC,NN
      INTEGER WETMOD,CONTONLY,CONTYPE,RAINHOUR

      DIMENSION Y(10)
      DIMENSION QSOL(25),RH(25),TSKYC(25),TIME(25),TALOC(25),TREF(25)
      DIMENSION RHREF(25),HRN(25)
      
      COMMON/CONT/CONTH,CONTW,CONTVOL,CONTDEP,CONTHOLE,CONTWET,RAINMULT,
     & WETMOD,CONTONLY,CONTYPE,RAINHOUR
      COMMON/CONTDEPTH/CONTDEPTH
      COMMON/EVAP1/PCTEYE,WEYES,WRESP,WCUT,AEFF,CUTFA,HD,PEYES,SKINW,
     & SKINT,HC,CONVAR      
      COMMON/DAYSTORUN/NN
      COMMON/ENVAR1/QSOL,RH,TSKYC,TIME,TALOC,TREF,RHREF,HRN
      COMMON/FUN1/QSOLAR,QIRIN,QMETAB,QRESP,QSEVAP,QIROUT,QCONV,QCOND
      COMMON/FUN2/AMASS,RELHUM,ATOT,FATOSK,FATOSB,EMISAN,SIG,FLSHCOND
      COMMON/FUN6/SPHEAT,ABSMAX,ABSMIN,O2MAX,O2MIN,LIVE
      COMMON/FUN4/TSKIN,R,WEVAP,TR,ALT,BP,H2O_BALPAST
      COMMON/RAINFALL/RAINFALL
      COMMON/OUTSUB/IT
      COMMON/TPREFR/TMAXPR,TMINPR,TDIGPR,TPREF,TBASK,TEMERGE
      COMMON/WINGFUN/RHO1_3,TRANS1,AREF,BREF,CREF,PHI,F21,F31,F41,F51
     &,SIDEX,WQSOL,PHIMIN,PHIMAX,TWING,F12,F32,F42,F52
     &,F61,TQSOL,A1,A2,A3,A4,A4B,A5,A6,F13,F14,F15,F16,F23,F24,F25,F26
     &,WINGCALC,WINGMOD

      GMASS=AMASS*1000.

      IF(TRANCT.EQ.NDAYY)THEN
       HOUR=T/60.
       TRANSIENT(IT)=Y(1)
       IF(Y(1).GT.50.)THEN
        CORE = 50.
       ELSE
        CORE = Y(1)
       ENDIF
       IF(LIVE .EQ. 1)THEN
        QMETAB = 0.0056*10.**(0.038*(CORE)-1.771)*GMASS**.82 ! THIS NEEDS UPDATING TO INCLUDE DEB-BASED CALC IF DEB MODEL RUNNING
       ELSE
        QMETAB = 0.
       ENDIF
       ZD2(IT)=QMETAB
       ZD3(IT)=WEVAP
       GEVAP=WEVAP*1000000.
       GCUT=WCUT*1000000.
       GRESP=WRESP*1000000.
       GEYES=WEYES*1000000.
c       IF((CONTH.GT.0.).AND.(RAINHOUR.EQ.1))THEN
c        CONTDEP=HRN(INT(HOUR)+1)*RAINMULT+CONTDEPTH-CONTHOLE ! ADDING TO LAST VALUE FROM DSUB2
c       ENDIF
c       CONTDEP=Y(3)
       IF(CONTDEP.LT.0.01)THEN
        CONTDEP=0.01
       ENDIF
       IF(CONTDEP.GT.CONTH*10)THEN
         CONTDEP=CONTH*10
       ENDIF
       CALL GEOM ! RECOMPUTE AMASS       
C       CONTDEPTH=CONTDEP
       ZD4(IT)=CONTDEP
      ENDIF
      IT = IT + 1
      RETURN
      END