      SUBROUTINE SHADEADJUST
C     NICHEMAPR: SOFTWARE FOR BIOPHYSICAL MECHANISTIC NICHE MODELLING

C     COPYRIGHT (C) 2018 MICHAEL R. KEARNEY AND WARREN P. PORTER

C     THIS PROGRAM IS FREE SOFTWARE: YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C     IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C     THE FREE SOFTWARE FOUNDATION, EITHER VERSION 3 OF THE LICENSE, OR (AT
C      YOUR OPTION) ANY LATER VERSION.

C     THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
C     WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C     MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
C     GENERAL PUBLIC LICENSE FOR MORE DETAILS.

C     YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C     ALONG WITH THIS PROGRAM. IF NOT, SEE HTTP://WWW.GNU.ORG/LICENSES/.

C     ADJUSTS THE AMOUNT OF SHADE.

      IMPLICIT NONE

      DOUBLE PRECISION A1,A2,A3,A4,A4B,A5,A6,ACTHR,AL,ALT,AMASS,ANDENS
      DOUBLE PRECISION AREF,ASIL,ASILP,ATOT,BP,BREF,CREF,CUSTOMGEOM
      DOUBLE PRECISION DEPSEL,DEPSUB,DSHD,EGGSHP,EMISAN,EMISSB,EMISSK
      DOUBLE PRECISION F12,F13,F14,F15,F16,F21,F23,F24,F25,F26,F61,F31
      DOUBLE PRECISION F32,F41,F42,F51,F52,FATOSB,FATOSK,FLSHCOND,FLUID
      DOUBLE PRECISION G,H2O_BALPAST,HRN,HSHSOI,HSOIL,MAXSHD,MSHSOI
      DOUBLE PRECISION MSOIL,NEWDEP,PHI,PHIMAX,PHIMIN,PSHSOI,PSOIL
      DOUBLE PRECISION PTCOND,PTCOND_ORIG,QCOND,QCONV,QIRIN,QIROUT
      DOUBLE PRECISION QMETAB,QRESP,QSEVAP,QSOL,QSOLAR,QSOLR,R,RELHUM,RH
      DOUBLE PRECISION RHO1_3,RHREF,SHADE,SHP,SIDEX,SIG,SUBTK,TA,TALOC
      DOUBLE PRECISION TANNUL,TBASK,TC,TCORES,TDIGPR,TEMERGE,TIME,TMAXPR
      DOUBLE PRECISION TMINPR,TOBJ,TPREF,TQSOL,TR,TRANS1,TREF,TSHSOI
      DOUBLE PRECISION TSKIN,TSKY,TSKYC,TSOIL,TSUB,TSUBST,TWING,VEL,VLOC
      DOUBLE PRECISION VREF,WEVAP,WQSOL,Z,ZSOIL,EGGPTCOND,POT
      DOUBLE PRECISION TCOND,SHTCOND
      
      INTEGER IHOUR,GEOMETRY,MICRO,NODNUM,WINGCALC,WINGMOD

      CHARACTER*1 BURROW,DAYACT,CLIMB,CKGRSHAD,CREPUS,NOCTURN
      
      DIMENSION ACTHR(25),CUSTOMGEOM(8),DEPSEL(25),HRN(25),HSHSOI(10)
      DIMENSION HSOIL(10),MSHSOI(10),MSOIL(10),PSHSOI(10),PSOIL(10)
      DIMENSION QSOL(25),RH(25),RHREF(25),SHP(3),TALOC(25),TCORES(25)
      DIMENSION TIME(25),TREF(25),TSHSOI(10),TSKYC(25),TSOIL(10)
      DIMENSION TSUB(25),VREF(25),Z(25),ZSOIL(10),EGGSHP(3)
      DIMENSION TCOND(10),SHTCOND(10)

      COMMON/BEHAV1/DAYACT,BURROW,CLIMB,CKGRSHAD,CREPUS,NOCTURN
      COMMON/BEHAV2/GEOMETRY,NODNUM,CUSTOMGEOM,SHP,EGGSHP
      COMMON/BEHAV3/ACTHR
      COMMON/DEPTHS/DEPSEL,TCORES
      COMMON/ENVAR1/QSOL,RH,TSKYC,TIME,TALOC,TREF,RHREF,HRN
      COMMON/ENVAR2/TSUB,VREF,Z,TANNUL,VLOC
      COMMON/FUN1/QSOLAR,QIRIN,QMETAB,QRESP,QSEVAP,QIROUT,QCONV,QCOND
      COMMON/FUN2/AMASS,RELHUM,ATOT,FATOSK,FATOSB,EMISAN,SIG,FLSHCOND
      COMMON/FUN3/AL,TA,VEL,PTCOND,SUBTK,DEPSUB,TSUBST,PTCOND_ORIG,
     & EGGPTCOND,POT
      COMMON/FUN4/TSKIN,R,WEVAP,TR,ALT,BP,H2O_BALPAST
      COMMON/SHADE/MAXSHD,DSHD
      COMMON/SOIL/TSOIL,TSHSOI,ZSOIL,MSOIL,MSHSOI,PSOIL,PSHSOI,HSOIL,
     & HSHSOI,TCOND,SHTCOND
      COMMON/TPREFR/TMAXPR,TMINPR,TDIGPR,TPREF,TBASK,TEMERGE
      COMMON/TREG/TC
      COMMON/WDSUB1/ANDENS,ASILP,EMISSB,EMISSK,FLUID,G,IHOUR
      COMMON/WDSUB2/QSOLR,TOBJ,TSKY,MICRO
      COMMON/WSOLAR/ASIL,SHADE
      COMMON/WUNDRG/NEWDEP
      COMMON/WINGFUN/RHO1_3,TRANS1,AREF,BREF,CREF,PHI,F21,F31,F41,F51
     &,SIDEX,WQSOL,PHIMIN,PHIMAX,TWING,F12,F32,F42,F52
     &,F61,TQSOL,A1,A2,A3,A4,A4B,A5,A6,F13,F14,F15,F16,F23,F24,F25,F26
     &,WINGCALC,WINGMOD
     
      IF(MAXSHD.GT.100.)THEN
       MAXSHD=100.
      ENDIF

      IF(SHADE.LT.MAXSHD)THEN
C      INCREASE SHADE, AND DO A SOLUTION IN THE NEW ENVIRONMENT
       SHADE=SHADE+DSHD
       IF(SHADE.GT.MAXSHD)THEN
        SHADE=MAXSHD
       ENDIF
C      GET THE CLIMATE FOR CHANGED SHADE
       CALL ABOVEGROUND
       IF(QSOL(IHOUR).GT.0.00000)THEN
        CALL SOLAR
       ENDIF
      ENDIF
      CALL RADIN

      RETURN
      END