C	  PART OF DOPRI5
        SUBROUTINE SOLOUT (NR,XOLD,X,Y,N,CON,ICOMP,ND,RPAR,IPAR,IRTRN)
C --- PRINTS SOLUTION AT EQUIDISTANT OUTPUT-POINTS BY USING "CONTD5"
      IMPLICIT NONE
C        IMPLICIT REAL*8 (A-H,O-Z)
      DOUBLE PRECISION XOLD,X,Y,CON,RPAR,XOUT
      INTEGER NR,N,ICOMP,ND,IPAR,IRTRN
        DIMENSION Y(N),CON(5*ND),ICOMP(ND),RPAR(8)
        COMMON /INTERN/XOUT
        IF (NR.EQ.1) THEN
           WRITE (6,99) X,Y(1),Y(2),Y(3),Y(4),NR-1
           XOUT=X+5.0D0
        ELSE
 10        CONTINUE
           IF (X.GE.XOUT) THEN
C             WRITE (6,99) XOUT,CONTD5(1,XOUT,CON,ICOMP,ND),
C    &CONTD5(2,XOUT,CON,ICOMP,ND),CONTD5(2,XOUT,CON,ICOMP,ND),
C    &REAL(NR-1,4)
              XOUT=XOUT+5.0D0
              GOTO 10
           END IF
        END IF
 99     FORMAT(1X,'X =',F6.2,'    Y =',4E18.10,'    NSTEP =',I4)
        RETURN
        END