#' COND_ecto
#'
#' R version of Fortran COND.f (ectotherm model) for calculating conductive heat exchange.
#'
#' @encoding UTF-8
#' @param AV ventral surface area (m2)
#' @param DEP depth of substrate across which conduction is occurring (m)
#' @param TSKIN solar absorptivity of ventral fur (fractional, 0-1)
#' @param TSUBST  substrate temperature (°C)
#' @param SUBTK skin temperature (°C)
#' @export
COND_ecto <- function(
    AV = 0.001325006,
    DEP = 0.025,
    TSKIN = 25,
    TSUBST = 10,
    SUBTK = 0.1){

  # C     NICHEMAPR: SOFTWARE FOR BIOPHYSICAL MECHANISTIC NICHE MODELLING
  #
  # C     COPYRIGHT (C) 2018 MICHAEL R. KEARNEY AND WARREN P. PORTER
  #
  # C     THIS PROGRAM IS FREE SOFTWARE: YOU CAN REDISTRIBUTE IT AND/OR MODIFY
  # C     IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
  # C     THE FREE SOFTWARE FOUNDATION, EITHER VERSION 3 OF THE LICENSE, OR (AT
  # C     YOUR OPTION) ANY LATER VERSION.
  #
  # C     THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
  # C     WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
  # C     MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
  # C     GENERAL PUBLIC LICENSE FOR MORE DETAILS.
  #
  # C     YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
  # C     ALONG WITH THIS PROGRAM. IF NOT, SEE HTTP://WWW.GNU.ORG/LICENSES/.
  #
  # C     SUBROUTINE FOR CALCULATING HEAT TRANSFER TO THE SUBSTRATE
  # C     ORIGINALLY DEVELOPED FOR A GARTER SNAKE, THAMNOPHIS ELEGANS

  # C     SOIL THERMAL COND. (SUBTK =0.35W/M-C)
  # C     WOOD ALSO HAS A THERMAL COND. 0.10-0.35 W/M-C
    QCOND <- AV * (SUBTK / DEP) * (TSKIN - TSUBST) #! CONDUCTION HEAT FLOW, FROM SKIN TO 2.5 CM INTO SUBSTRATE
 return(QCOND)
}

